### ISSUE TITLE
Fehlendes Projekt (Inserter) und Rest-Files im Repository

### ISSUE THREAD

**Issue by tomwendel** [susch19/TurtlesBrain#5]
Im aktuellen Stand des Projektes fehlt leider das referenzierte Projekt des Inserteres. Dafür gibt es jede Menge alte Artefakte von Projekten, die in der Solution schon lange keine Anwendung mehr finden (ConsoleApplication1, WindowsFormsApplication1, turtle, DBTeast,...)

**Comment by Gallimathias** [comment]
Ok wir setzen uns gleich mal drann

**Comment by susch19** [comment]
Die alten Artefakte waren nicht alt, aber ich habe nur die Projekte gelöscht, aber nicht die Dateien, dadurch wurde Müll mit eingescheckt, hatte ich wohl übersehen. Bei mir funktioniert der DatabaseInserter (vorkompilierte Datei mit allem, was benötigt wird, ist auch in TurtlesBrain drin)

**Comment by susch19** [comment]
Jetzt habe ich bemerkt, was das Problem war, die dll muss noch hinzugefügt werden, da gitignore die ja allgemein rausfiltert. Beim nächsten Commit sollte es dann wieder funktionieren.
